language: node_js
sudo: false
node_js:
  - "6"
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - yarn
script:
  - yarn build-for-deploy
  - yarn test -- --coverage
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
after_success:
  - ./node_modules/.bin/surge --project ./build --domain film-roulette-bz.surge.sh/